# Pre-commit checks
pre-commit:
  parallel: true
  jobs:
    - run: npx stylelint --fix {staged_files}
      glob:
        - "*.css"
        - "*.scss"
      stage_fixed: true

    - run: npx @biomejs/biome check "{staged_files}" --write
      glob:
        - "*.js"
        - "*.jsx"
        - "*.ts"
        - "*.tsx"
      stage_fixed: true

# Pre-push checks
pre-push:
  parallel: true
  commands:
    branchName:
      run: npx validate-branch-name

# Validate commit messages
commit-msg:
  commands:
    "lint commit message":
      run: npx --no-install commitlint --color --edit {1}
