# Pre-commit checks
pre-commit:
  parallel: true
  jobs:
    - run: npm run stylelint --fix {staged_files}
      glob:
        - "*.css"
        - "*.scss"
      stage_fixed: true

    - run: npm run biome check "{staged_files}" --write
      glob:
        - "*.js"
        - "*.jsx"
        - "*.ts"
        - "*.tsx"
      stage_fixed: true

# Validate commit messages
commit-msg:
  commands:
    "lint commit message":
      run: npx --no-install commitlint --color --edit {1}
