name: Build, typescript, eslint & stylelint checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  # Install and cache npm dependencies
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Cache npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-npm
      - name: Install dependencies if cache invalid
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: bun install

  # Build Storybook
  build:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Restore npm dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-npm
      - name: Run ESLint
        run: bun run lint
      - name: Run Stylelint
        run: bun run lint-css
      - name: Build Storybook
        run: bun run build-storybook
      - name: Build Package
        run: bun run build-package
